language: python
matrix:
  include:
  - python: 2.7
    env:
    - secure: "NQm0Bn+A9oVNIIMTQTyTiFyNYGZPVI94ejKkpEVErj69eAnvAHJvQPkCwsOlMciLFyzR9fYmICQEK97nCtVF8UTU1jci7lcyrRAuBcKgtugyhykNA97Hd0RygcIwRspE4XphaRxB1eaBsUI/Rbb4OFDIps+HhjTMtKQ5KhptEcGdyuvjOAy5sf1yRSWevmH+Az5IVr4GRD63oYDuwEmS2snOX/RZ7CZ5DMNxhi/5E0MWRWwCHp0k9+vQfCpqljjmNdk0WK2mEuiXMduRjGNni+2odCNFmpYoDRYo9UsOVGub8DUH5MPciW+WzRf9EPoA9MzGlp6npyHMnAMqXuOIWR6yyOoYnBcWi6Ft9NzWqvxXjV8y8EAyf0DpbDk58gu1p4GQ/o4/bHeVCCinBL31ok70YF79KU4ogzT9UK05hY1VSboLhaG/vz8847fQNijRrrl/Dx6fKwRau6WdQyUSERuVLq6HHQBTnIHb/diotB6NjW+1+Yzaxw+VwBa+MYDxb7LLFs44zb9n0Lw+p8hhV7FwDSE4wQT1327AUeJqudhVuwSMZECBOVlzy96Jozb4G0oNXdclFsoTGAFy3H3bDIXLyO4SQIa7Ah/PDMtdIkq4oRFN6ml9336BX6u1qCTI37X8IVcjVCgs2MqVS9FDeSWjJ5KPByGjRmQvn7rc1Go="
    - secure: "CIUi92OsA29P5bgVZfwjYNl5aNTR17jh3aZO0nyrKmrco2Fron2P3QM2cG1SiKUGjrNWANuQu6hX6H9BhJEKB34Tni+xOMx/476Qbe48JZU3WmwQr/iktULRCbxaxGVqx58VJ8GvVR76Qw4pXDITBWZaG9N3HqX63Cu+P87Ey+FfdzdBwRdfphsGZXwkzRhxyTg8LvToM0+7pFAgcHdfOZ6ExPbqVkos8fyL3WTEXIQJAAf9y5X4mVCPMO2Bnry1OxK4afgHuZ7vxojjH+fHY8Y5TjB/H+AaMPugplPKDtFMyrPLmwS+I/UOU2iiTbvJP5y6iiS7Eago8MKg90qFKYgoxTREMNNY/9SUk3cN8F6B5v9vRvo/NYRR3/VC2c1noMWAbvj0zabVxxaJgjzGM5hle8dqLkyPheli9tBjBzHq4Bc9nruwTR6v98FJ372I9QIZ7gumZyoRVg4HnJDZ87YSuZfrK1Ns0TCxuqQLhL1bwRyLQarmYgNRRsJiqW8DK5G2c+Y+6KnuFZUwcVRhCqnHwof7DA3s/Ir92wzkSFC02fJT2hYuv7i2vhlX4bv97FVPkylwbg5oRjEEDXjdGRbZF1ol2SsmSrDb+Rja4Nxxk8jzu5H5Xkw1YcrBaidOWOpJ0k1Tbt0OmOrWaBg7VZptnTEUoRY0NtS2irzQig0="
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
    - BOB_UPLOAD_WHEEL="--universal"
  - python: 3.3
  - python: 3.4
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev libatlas-dev libatlas-base-dev liblapack-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy coverage
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- ./bin/buildout buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.db.biosecurid.face import get_config; print(get_config())'
- ./bin/bob_dbmanage.py biosecurid.face download
- ./bin/coverage run --source=bob.db.biosecurid.face ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
